check docker build args

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -29,7 +29,7 @@ RUN mkdir -p experiment_runs/
 # Install Algorithmic efficiency repo
 RUN echo "Setting up algorithmic_efficiency repo"
 ARG branch="main"
-ARG framework=""
+ARG framework="both"
 ARG git_url=https://github.com/mlcommons/algorithmic-efficiency.git
 RUN git clone $git_url && cd algorithmic-efficiency 
 RUN cd algorithmic-efficiency && git checkout $branch
@@ -46,11 +46,13 @@ RUN if [ "$framework" = "jax" ] ; then \
         && cd algorithmic-efficiency \
         && pip install -e '.[jax_cpu]' \
         && pip install -e '.[pytorch_gpu]' -f 'https://download.pytorch.org/whl/torch_stable.html'; \
-    else \
+    elif [ "$framework" = "both" ]\
         echo "Installing Jax GPU and Pytorch GPU" \
         && cd algorithmic-efficiency \
         && pip install -e '.[jax_gpu]' -f 'https://storage.googleapis.com/jax-releases/jax_cuda_releases.html' \
         && pip install -e '.[pytorch_gpu]' -f 'https://download.pytorch.org/whl/torch_stable.html'; \
+    else 
+        echo "Invalid build-arg $framework: framework should be either jax, pytorch or both." >&2 && exit 1 \
     fi
 
 RUN cd algorithmic-efficiency && pip install -e '.[wandb]'
