update installation instructions

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -69,27 +69,17 @@ RUN cd /algorithmic-efficiency && git checkout $branch
 RUN if [ "$framework" = "jax" ] ; then \
         echo "Installing Jax GPU" \
         && cd /algorithmic-efficiency \
-        && pip install -e '.[pytorch_cpu]' --extra-index-url https://download.pytorch.org/whl/cpu \
+        && pip install -e '.[pytorch_cpu, full]' --extra-index-url https://download.pytorch.org/whl/cpu \
         # Todo: remove temporary nightly install
-        # pip install -e '.[jax_gpu]'
-        && c; \
+        &&  pip install -U --pre jax jaxlib "jax-cuda12-plugin[with-cuda]" jax-cuda12-pjrt -i https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/; \
     elif [ "$framework" = "pytorch" ] ; then \
         echo "Installing Pytorch GPU" \
         && cd /algorithmic-efficiency \
-        && pip install -e '.[pytorch_gpu, jax_cpu]'; \
-    elif [ "$framework" = "both" ] ; then \
-        echo "Installing Jax GPU and Pytorch GPU" \
-        && cd /algorithmic-efficiency \
-        && pip install -e '.[pytorch_gpu]' \
-        # Todo: remove temporary nightly install 
-        # pip install -e '.[jax_gpu]'
-        && pip install -U --pre jax jaxlib "jax-cuda12-plugin[with-cuda]" jax-cuda12-pjrt -i https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/; \
+        && pip install -e '.[pytorch_gpu, jax_cpu, full]'; \
     else \
-        echo "Invalid build-arg $framework: framework should be either jax, pytorch or both." >&2 \
+        echo "Invalid build-arg $framework: framework should be either jax or pytorch." >&2 \
         && exit 1 ; \
     fi
-
-RUN cd /algorithmic-efficiency && pip install -e '.[full]'
 
 RUN cd /algorithmic-efficiency && git fetch origin 
 RUN cd /algorithmic-efficiency && git pull
