dockerfile fix

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -52,7 +52,8 @@ RUN if [ "$framework" = "jax" ] ; then \
         && pip install -e '.[jax_gpu]' -f 'https://storage.googleapis.com/jax-releases/jax_cuda_releases.html' \
         && pip install -e '.[pytorch_gpu]' -f 'https://download.pytorch.org/whl/torch_stable.html'; \
     else \
-        echo "Invalid build-arg $framework: framework should be either jax, pytorch or both." >&2 && exit 1 \
+        echo "Invalid build-arg $framework: framework should be either jax, pytorch or both." >&2 \
+        && exit 1 ; \
     fi
 
 RUN cd algorithmic-efficiency && pip install -e '.[wandb]'
